fintech_duckdb:
  target: dev
  outputs:
    dev:
      type: duckdb
      path: /opt/dbt/duckdb/fintech.duckdb
      threads: 4
      # Make the local silver parquet folder queryable as an external source
      extensions: ["httpfs","parquet"]
      # We'll read Parquet via dbt SQL using read_parquet() (DuckDB's function)

fintech_redshift:
  target: dev
  outputs:
    dev:
      type: redshift
      host: "{{ env_var('REDSHIFT_HOST') }}"
      user: "{{ env_var('REDSHIFT_USER') }}"
      password: "{{ env_var('REDSHIFT_PASSWORD') }}"
      port: "{{ env_var('REDSHIFT_PORT', 5439) | int }}"
      dbname: "{{ env_var('REDSHIFT_DB') }}"
      schema: "{{ env_var('REDSHIFT_SCHEMA', 'public') }}"
      threads: 4
      keepalives_idle: 0
      connect_timeout: 120
      retries: 1
